# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RUezoXCv26ydTC3MHpcXD__CYIvofxm6
"""

import pandas as pd

def pertama(data):

    file = open("negaraMean.csv","w")
    file.write(data)
    file.close()

def kedua(data):

    file = open("NegaraStandarDevisiasi.csv","w")
    file.write(data)
    file.close()

data = {"Negara": ["Indonesia", "Jepang", "India", "China", "Amerika Serikat", "Brazil", "Rusia"],
        "Ibu Kota": ["Jakarta", "Tokyo", "New Delhi", "Beijing", "Washington DC", "Brazilia", "Moskow"],
        "Benua": ["Asia", "Asia", "Asia", "Asia", "Amerika", "Amerika", "Asia"],
        "Luas": [1905, 377, 3287, 9597, 9834, 8515, 17098],
        "Populasi": [264, 143, 1252, 1357, 329, 210, 146] }

df = pd.DataFrame(data)
mean = df.groupby(['Benua']).mean()
std = df.groupby(['Benua']).std()

print("Berikut Data Framenya:\n")
print(df)
print("\nBerikut Data Mean:")
print(mean)
print("\nBerikut Data Standar Devisiasi")
print(std)
pertama(str(mean))
kedua(str(std))
print("\nFile Berhasil dibuat")

"""
@materi : algoritma dan pemograman
@judul : Data analisis
@hari/tanggal : jumat/17/12/2021
@nim : 065002100022
@author : Muhammad Tegar Hidayatullah
"""

import pandas as pd

data = {'Negara': ['Indonesia', 'Jepang', 'India', 'China', 'Amerika Serikat', 'Brazil', 'Rusia', 'Meksiko', 'Nigeria', 'Jerman', 'Aljazair', 'Inggris'],
        'Ibu Kota': ['Jakarta', 'Tokyo', 'New Delhi', 'Beijing', 'Washington, D.C.', 'Brazilia', 'Moskow', 'Meksiko City', 'Abuja', 'Berlin', 'Aljazair', 'London'],
        'Benua': ['Asia', 'Asia', 'Asia', 'Asia', 'Amerika', 'Amerika', 'Asia', 'Amerika', 'Afrika', 'Eropa', 'Afrika', 'Eropa'],
        'Luas': [1905, 377, 3287, 9597, 9834, 8515, 17098, 1964, 923, 357, 2381, 242],
        'Populasi': [264, 143, 1252, 1357, 329, 210, 146, 126, 200, 83, 43, 66]}

df = pd.DataFrame(data)
mean = df.groupby(['Benua']).mean()
std = df.groupby(['Benua']).std()

print('Berikut Data Data Framenya: ')
print(df)
print('')
print('Berikut Data Mean: ')
print(mean)
print('')
print('Berikut Data Standard Deviation: ')
print(std)
print('')